version: '3'
networks:
  pulsar:
    driver: bridge
  suscripcion:
    driver: bridge
  serviciodatos:
    driver: bridge
services:

# Start broker
  broker:
    image: apachepulsar/pulsar:2.7.0
    profiles: ["pulsar"]
    container_name: broker
    hostname: broker
    # restart: on-failure
    networks:
      - pulsar
    ports:
      - 8080:8080
      - 6650:6650
    # environment:
    #   - JAVA_HOME=/usr/lib/jvm/java-11-openjdk
    #   - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    # volumes:
    #   - ./pulsar/data:/pulsar/data
    #   - ./pulsar/config:/pulsar/conf
    command: /bin/bash -c "bin/pulsar standalone"


  suscripcion-db:
    container_name: suscripcion-db
    image: postgres:latest
    restart: always
    profiles: ["saludtechalpes"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=suscripcion-db
    ports:
      - "5432:5432"
    networks:
      - suscripcion
    depends_on:
      - broker
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
      - ./sql/create_extension.sql:/docker-entrypoint-initdb.d/create_extension.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  # Servicios de Salud Tech Alpes
  saludtechalpes:
    container_name: saludtechalpes
    hostname: saludtechalpes
    image: saludtechalpes/flask 
    profiles: ["saludtechalpes"]
    networks:
      - pulsar
      - suscripcion
    labels:
      SidecarDiscover: "false"
    depends_on:
      suscripcion-db:
          condition: service_healthy
    environment:
      - PULSAR_ADDRESS=broker
      - TESTING=true
      - DB_URL=postgresql://postgres:postgres@suscripcion-db:5432/suscripcion-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=suscripcion-db
      - DB_PORT=5432
      - DB_NAME=suscripcion-db
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"

  serviciodatos-db:
    container_name: serviciodatos-db
    image: postgres:latest
    restart: always
    profiles: ["serviciodatos"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=serviciodatos-db
    ports:
      - "5432:5432"
    networks:
      - serviciodatos
    depends_on:
      - broker
    volumes:
      - ./microservicio-servicio-datos/pgdata:/var/lib/postgresql/data/
      - ./microservicio-servicio-datos/sql/create_extension.sql:/docker-entrypoint-initdb.d/create_extension.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  serviciodatos:
    container_name: serviciodatos
    hostname: serviciodatos
    image: serviciodatos/flask 
    profiles: ["serviciodatos"]
    networks:
      - pulsar
      - serviciodatos
    labels:
      SidecarDiscover: "false"
    depends_on:
      serviciodatos-db:
          condition: service_healthy
    environment:
      - PULSAR_ADDRESS=broker
      - TESTING=true
      - DB_URL=postgresql://postgres:postgres@serviciodatos-db:5432/serviciodatos-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=serviciodatos-db
      - DB_PORT=5432
      - DB_NAME=serviciodatos-db
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
